version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    networks:
      - issie-tech

  app:
    depends_on: 
      - mongodb
    container_name: issie-tech-devops
    image: issie-tech-devops
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - issie-tech

networks:
  issie-tech:
    driver: bridge