version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - issie-tech

  app:
    depends_on: 
      - mongodb
    container_name: issie-tech-devops
    image: issie-tech-devops
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - issie-tech

networks:
  issie-tech:
    driver: bridge

volumes:
  mongo-data:
    driver: local